name: .NET

on:
  push:
    branches: [ DeployToAzure ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../webapp -r linux-x64 --self-contained true /p:UseAppHost=true
    - uses: azure/webapps-deploy@v2
      name: Deploy
      with:
        app-name: 'deck-of-cards-app-service'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './webapp'
